server:
  port: 8082

spring:
  application:
    name: category-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/expense-tracker

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
