server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: expense-service
          uri: lb://expense-service
          predicates:
            - Path=/api/expenses/**
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/api/categories/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
