server:
  port: 8081

spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/userdb}  # Environment variable fallback

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
